package com.movemoney.storage;

import com.movemoney.domain.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;


public class Fixtures {

    public static BacsTransaction debitBacsTransaction = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            Account.Id.autoGenerated(),
            Account.Id.autoGenerated(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(22.22), Currency.GBP));

    public static BacsTransaction creditBacsTransaction = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            Account.Id.autoGenerated(),
            Account.Id.autoGenerated(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(22.22), Currency.GBP));


    public static Account boris = Account.of(
            Account.Id.autoGenerated(),
            "Bob",
            Amount.of(BigDecimal.valueOf(1000.00), Currency.GBP));

    public static Account theresa = Account.of(
            Account.Id.autoGenerated(),
            "Theresa",
            Amount.of(BigDecimal.valueOf(2000.00), Currency.GBP));

    public static BacsTransaction borisToTheresaBacsTransaction_1 = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            boris.getId(),
            theresa.getId(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(22.22), Currency.GBP));

    public static BacsTransaction borisToTheresaBacsTransaction_2 = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            boris.getId(),
            theresa.getId(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(33.33), Currency.GBP));

    public static BacsTransaction theresaToBorisBacsTransaction_1 = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            theresa.getId(),
            boris.getId(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(44.44), Currency.GBP));

    public static BacsTransaction theresaToBorisBacsTransaction_2 = BacsTransaction.of(
            BacsTransaction.Id.autoGenerated(),
            theresa.getId(),
            boris.getId(),
            LocalDateTime.now(),
            Amount.of(BigDecimal.valueOf(55.55), Currency.GBP));
}
